protected route works
ColmanDevClub/Website pull request #31
Opened 2024-09-26 19:14 UTC by ShirYahav

works with if the user is signed in or not, for now without a role (user, admin)

2024-09-27 08:57 UTC, GilHeller requested changes

2024-09-27 08:57 UTC, GilHeller commented on src/lib/auth/pages/Logout/logout.jsx
> +        if (user) {
The if statement is always true. The default user is `{}` which is `true` in the condition predicate.

2024-09-27 08:57 UTC, GilHeller commented on src/lib/auth/pages/Logout/logout.jsx
> +        console.log(e.message);
Use `console.error()` instead.

https://www.atatus.com/blog/javascript-logging-basic-tips/

2024-09-27 08:57 UTC, GilHeller commented on src/lib/auth/authContext.js
> +      console.log(currentUser);
What does the variable `currentUser` contains? 
Does it contains sensitive information like password?

2024-09-27 08:57 UTC, GilHeller commented on src/lib/auth/authContext.js
Nice! 
The comments are unnecessary, the code is readable even without them

2024-10-07 10:28 UTC, ShirYahav commented on src/lib/auth/authContext.js
> +      console.log(currentUser);
it contains properties about the authenticated user but not any sensitive information like password.  Firebase doesnt expose the password in the currentUser

2024-10-07 10:28 UTC, ShirYahav commented on src/lib/auth/authContext.js
took the comments down :)

2024-10-07 10:31 UTC, ShirYahav commented on src/lib/auth/pages/Logout/logout.jsx
> +        if (user) {
any comment about logout is not relevant I deleted the Logout folder and took a different approach in the other pull request I uploaded which Bar commented on

2024-10-07 13:31 UTC, closed without merging