Responsive auth menu
ColmanDevClub/Website pull request #32
Opened 2024-09-26 20:43 UTC by ShirYahav

logout functionality + responsive menu works :)

2024-10-03 16:12 UTC, BarSh0 commented on src/ui/Navbar/index.js
> +      navigate("/");
You do not need to navigate the user to the home page, but the fact that he has disconnected, the application should throw him there, because of the ProtectedRoutes

2024-10-03 16:15 UTC, BarSh0 commented on src/ui/Navbar/index.js
> +    try {
move the try-catch to the context,
you do not want to do this every time that you wanna use the log out,

2024-10-03 16:17 UTC, BarSh0 commented on src/utils/protectedRoutes.js
> +import React from 'react';
change the file name like the component: ProtectedRoute.js

2024-10-03 16:23 UTC, BarSh0 requested changes
seems like your prettier config is different from the project.
pull from the main the .prettierrc.json file,
and then let me CR again without the prettier changes.

2024-10-07 10:42 UTC, ShirYahav commented on src/ui/Navbar/index.js
> +      navigate("/");
Yep its doing it automatically

2024-10-07 13:54 UTC, merged